spring:
  ##数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/manicure?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  ##设置日志输出格式
  output:
    ansi:
      enabled: detect
##mybatis配置文件位置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
