spring:
  ##数据源配置
  datasource:
    name: manicure
    url: jdbc:mysql://localhost:3306/manicure?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: datasource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

  ##设置日志输出格式
  output:
    ansi:
      enabled: detect
##mybatis配置文件位置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
